/** @type {import('@commitlint/types').UserConfig} */
module.exports = {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'type-enum': [
      2,
      'always',
      [
        'feat',
        'fix',
        'docs',
        'style',
        'refactor',
        'perf',
        'test',
        'chore',
        'ci',
        'revert',
        'build',
        'wip',
      ],
    ],
    'scope-enum': [
      2,
      'always',
      [
        'api',
        'web',
        'shared-types',
        'ui',
        'infra',
        'ci',
        'deps',
        'auth',
        'ocr',
        'photo',
        'creator',
        'business',
        'agriculture',
        'entertainment',
        'billing',
        'queue',
        'storage',
        'db',
        'docs',
      ],
    ],
    'subject-case': [2, 'always', 'lower-case'],
    'header-max-length': [2, 'always', 100],
  },
};
